"""
Experiment tracking wrapper for AirSketch.
Wraps Weights & Biases. All training code calls this module — never wandb directly.
"""

import wandb
from pathlib import Path


class ExperimentLogger:
    """
    Thin wrapper around W&B. Instantiate once at the start of a training run.

    Usage:
        logger = ExperimentLogger(config)
        logger.log_epoch(epoch=1, train_metrics={...}, val_metrics={...}, lr=1e-3)
        logger.log_model(checkpoint_path="checkpoints/best.pt", metric_value=6.4)
        logger.finish()
    """

    def __init__(
        self,
        config: dict,
        run_name: str | None = None,
        tags: list[str] | None = None,
    ):
        """
        Args:
            config:   Full config dict (loaded from default.yaml). Logged as hyperparameters.
            run_name: Optional human-readable name. Auto-generated by W&B if None.
            tags:     Optional list of tags, e.g. ["sweep", "ablation-spatial-only"].
        """
        self.run = wandb.init(
            project="AirSketch",
            entity="airsketch",
            name=run_name,
            config=config,
            tags=tags or [],
            resume="allow",
        )
        self.run_name = self.run.name
        self.run_id = self.run.id
        print(f"W&B run started: {self.run.url}")

    # ── Per-epoch logging ─────────────────────────────────────────────────────

    def log_epoch(
        self,
        epoch: int,
        train_metrics: dict,
        val_metrics: dict,
        lr: float,
    ) -> None:
        """
        Log all metrics for one epoch.

        Expected keys in train_metrics / val_metrics:
            mpjpe        (float) — mean per-joint position error in pixels
            jitter_index (float) — mean frame-to-frame displacement variance px²
            gesture_acc  (float) — draw/idle classification accuracy [0, 1]
            loss         (float) — combined joint loss value

        Args:
            epoch:         Current epoch number (1-indexed).
            train_metrics: Dict of training metrics for this epoch.
            val_metrics:   Dict of validation metrics for this epoch.
            lr:            Current learning rate (from scheduler).
        """
        payload = {"epoch": epoch, "lr": lr}

        for key, value in train_metrics.items():
            payload[f"train/{key}"] = value

        for key, value in val_metrics.items():
            payload[f"val/{key}"] = value

        wandb.log(payload, step=epoch)

    # ── Step-level logging (optional, for loss curves within an epoch) ────────

    def log_step(
        self,
        step: int,
        loss: float,
        gesture_loss: float,
        regression_loss: float,
    ) -> None:
        """Log per-batch losses. Call every N steps (e.g. every 10 batches)."""
        wandb.log(
            {
                "step/loss": loss,
                "step/gesture_loss": gesture_loss,
                "step/regression_loss": regression_loss,
            },
            step=step,
        )

    # ── Model checkpointing ───────────────────────────────────────────────────

    def log_model(
        self,
        checkpoint_path: str | Path,
        metric_value: float,
        metric_name: str = "val/mpjpe",
    ) -> None:
        """
        Save a model checkpoint as a W&B artifact.
        Call this whenever a new best checkpoint is saved.

        Args:
            checkpoint_path: Path to the .pt file on disk.
            metric_value:    The metric value that triggered this checkpoint save.
            metric_name:     Name of the metric used for best-model selection.
        """
        artifact = wandb.Artifact(
            name=f"airsketch-model-{self.run_id}",
            type="model",
            metadata={metric_name: metric_value},
        )
        artifact.add_file(str(checkpoint_path))
        self.run.log_artifact(artifact)
        print(
            f"Checkpoint logged to W&B artifact: {checkpoint_path} "
            f"({metric_name}={metric_value:.4f})"
        )

    # ── Summary metrics (end of run) ──────────────────────────────────────────

    def log_summary(self, test_metrics: dict) -> None:
        """
        Log final test-set metrics at the end of a run.
        These appear in the W&B run summary panel.

        Args:
            test_metrics: Dict with keys mpjpe, jitter_index, gesture_acc, latency_ms, sus_score.
        """
        for key, value in test_metrics.items():
            wandb.run.summary[f"test/{key}"] = value

    # ── Cleanup ───────────────────────────────────────────────────────────────

    def finish(self) -> None:
        """Call at the end of every training script. Flushes remaining logs."""
        wandb.finish()
        print(
            f"W&B run finished. "
            f"View at: https://wandb.ai/airsketch/AirSketch/runs/{self.run_id}"
        )
